apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-reticulas
  labels:
    api: reticulas
    type: local
spec:
  storageClassName: bd
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/docker/reticulas/bd/"