apiVersion: v1
kind: Service
metadata:
  name: bd-reticulas
  labels:
    api: reticulas
    rol: bd
    nivel: backend
spec:
  ports: 
  - port: 3306
  selector: 
    api: reticulas
    rol: bd
    nivel: backend