apiVersion: v1
kind: Service
metadata:
  name: api-reticulas
  labels:
    api: reticulas
    rol: servicio-web
    nivel: backend
spec:
  type: NodePort
  ports: 
  - port: 80
    targetPort: 80
  selector: 
    api: reticulas
    rol: servicio-web
    nivel: backend